image = imread('nature.jpeg');
image = rgb2gray(image);
gaussian_noisy_image = imnoise(image, 'gaussian', 0, 0.01);
rayleigh_noise = raylrnd(25, size(image));
rayleigh_noisy_image = double(image) + rayleigh_noise;
rayleigh_noisy_image = uint8(min(rayleigh_noisy_image, 255));
shape = 2;
scale = 15;
erlang_noise = gamrnd(shape, scale, size(image));
erlang_noisy_image = double(image) + erlang_noise;
erlang_noisy_image = uint8(min(erlang_noisy_image, 255));
figure;
subplot(2, 2, 1);
imshow(image);
title('Original Image');
subplot(2, 2, 2);
imshow(gaussian_noisy_image);
title('Gaussian Noise');
subplot(2, 2, 3);
imshow(rayleigh_noisy_image);
title('Rayleigh Noise');
subplot(2, 2, 4);
imshow(erlang_noisy_image);
title('Erlang Noise');
