image = imread('nature.jpeg');
grayImage = rgb2gray(image);
newSize = [300 400];   
resizedImage = imresize(grayImage, newSize, 'bilinear');
figure;
subplot(1, 2, 1);
imshow(grayImage);
title('Original Image');
subplot(1, 2, 2);
imshow(resizedImage);
title('Resized Image (Linear Interpolation)');
