image = imread('nature.jpeg');
grayImage = rgb2gray(image);
meanFilterKernel = ones(5, 5) / 9;
filteredImage = imfilter(grayImage, meanFilterKernel);
figure;
subplot(1, 2, 1);
imshow(grayImage);
title('Original Image');
subplot(1, 2, 2);
imshow(filteredImage);
title('Mean Filtered Image');