image = imread('nature.jpeg');
grayImage = rgb2gray(image);
laplacianKernel = fspecial('laplacian', 0.2);   
filteredImage = imfilter(grayImage, laplacianKernel);
figure;
subplot(1, 2, 1);
imshow(grayImage);
title('Original Image');
subplot(1, 2, 2);
imshow(filteredImage, []);
title('Laplacian Filtered Image');
